Added some error checks to ci script

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -83,12 +83,26 @@ jobs:
           echo "Creating CosmosDB database account $cosmosname (This can take awhile.)"
 
           $acctDetails = az cosmosdb create --name $cosmosname --location $region --resource-group $gaResourceGroup --capabilities EnableServerless --tags Package=CosmosPersistence RunnerOS=${{ runner.os }} $dateTag | ConvertFrom-Json
+
+          if(!$acctDetails || !$acctDetails.documentEndpoint)
+          {
+            echo "Account creation failed. $acctDetails"
+            exit 1;
+          }
+
           $documentEndpoint = $acctDetails.documentEndpoint
 
           echo "::add-mask::$documentEndpoint"
           echo "Getting CosmosDB access keys"
 
           $keyDetails = az cosmosdb keys list --name $cosmosname --resource-group $gaResourceGroup | ConvertFrom-Json
+
+          if(!$keyDetails || !$keyDetails.primaryMasterKey)
+          {
+            echo "Unable to retrieve access keys.  $keyDetails"
+            exit 1;
+          }
+
           $cosmosKey = $keyDetails.primaryMasterKey
 
           echo "::add-mask::$cosmosKey"
@@ -103,6 +117,7 @@ jobs:
           echo "Getting storage account keys"
 
           $storageKeyDetails = az storage account keys list --account-name $storagename --resource-group $gaResourceGroup | ConvertFrom-Json
+
           $storageKey = $storageKeyDetails[0].value
 
           echo "::add-mask::$storageKey"
